apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpademo
spec:
  maxReplicas: 10
  minReplicas: 7
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejsapplication-deployment
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetCPUUtilizationPercentage: 50
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 60
	  
